name: build-test

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "LICENSE", "cliff.toml", "CHANGELOG.md" ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        lazarus-versions: [stable, 2.2.0, 2.0.12]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        with-cache: false
    - name: Build the Test App
      run: lazbuild -B --bm=Debug "tests/TestNosoDataCLI.lpi"
    - name: Run the Test App
      run: cd bin && ./TestNosoData-CLI "--all" "--format=plain"
